### ISSUE TITLE
Input function response

### ISSUE THREAD

**Issue by FelippeChemello** [TrelisResearch/tgi-chat-ui-function-calling#2]
Hi,
Thank you for your work.
I would like to know how to input the function response to the model process it and answer the user request.
Is there a prompt `tag` to input the function return?

**Comment by RonanKMcGovern** [comment]
Howdy Felippe, there isn't a tag.

I use one of two options:

a) pass everything to the model: i) the conversation history, ii) the user question, iii) the function call, perhaps prepended by 'call the following function', iv) the function response, perhaps prepended by 'Function response:\n\n' (as a user message), then you can generate a new assistant response.

b) i) the conversation history, ii) the user question followed by the response to the function call, prepended by "Make use of this info in your answer", then you can generate a new assistant response.

c)  if you're short on context you may not be able to include the conversation history.
